Change Error message namespace + policy names
open-cluster-management-io/governance-policy-propagator pull request #124
Opened 2023-08-10 17:53 UTC by yiraeChristineKim

Description: Change error message "the combined length of the policy namespace and name <namespace>.<name> cannot exceed 63 characters" to the combined length of the policy namespace and name <namespace>.<name> cannot exceed 62 characters
Ref: https://issues.redhat.com/browse/ACM-6838

2023-08-10 18:10 UTC, dhaiducek requested changes

2023-08-10 18:24 UTC, dhaiducek approved these changes
/hold for Console PR to be reviewed (in case a review results in the wording being changed)

2023-08-11 16:35 UTC, dhaiducek commented
/unhold as console update was approved

2023-08-15 18:00 UTC, JustinKuli approved these changes

2023-08-15 18:00 UTC, JustinKuli commented
/unhold

2023-08-15 18:20 UTC, dhaiducek commented
/unhold

2023-08-15 18:25 UTC, merged